//
// Created by elfxe on 14.02.2024.
//

#ifndef DOTAPARSERSERVER_DEFINITIONS_H
#define DOTAPARSERSERVER_DEFINITIONS_H

#define DEFAULT_VALVE_DOTA_POST_TIMEOUT_SECONDS 30

#endif //DOTAPARSERSERVER_DEFINITIONS_H
